name: baguettefy

services:
  baguettefy:
    restart: always
    build: .
    volumes:
      - db_cache:/app/CachedDatabase
    depends_on:
      - libretranslate

  libretranslate:
    image: libretranslate/libretranslate
    restart: always
    ports:
      - "5511:5511"  # Optional: exposes it to host, useful for testing
    environment:
      - LT_LOAD_ONLY=en,fr
      - LT_DISABLE_USAGE=true

volumes:
  db_cache:
