name: baguettefy

services:
  baguettefy:
    restart: always
    build: .
    volumes:
      - db_cache:/app/CachedDatabase
      - nugget_cache:/app/CachedNuggets
    
volumes:
  db_cache:
  nugget_cache:
    
    