// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Baguettefy.Data.Quests;
//
//    var questsData = AllQuestsData.FromJson(jsonString);

using Baguettefy.Data.DofusDb;

namespace Baguettefy.Data.Quests
{
    using Newtonsoft.Json;

    public partial class AllQuestsData
    {
        [JsonProperty("data")]
        public QuestData[] Quests { get; set; }
    }

    public partial class QuestData
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("name")]
        public Name Name { get; set; }

        [JsonProperty("steps")]
        public Step[] Steps { get; set; }

        [JsonProperty("startCriterion")]
        public string StartCriterion { get; set; }
    }

    public partial class Step
    {
        [JsonProperty("name")]
        public Name Name { get; set; }
    }
}
