// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using AlmanaxDude.Data.Items;
//
//    var equipmentData = ItemData.FromJson(jsonString);

namespace Baguettefy.Data.Items
{
    using System;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ItemData
    {
        [JsonProperty("ankama_id")]
        public long AnkamaId { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }
        
        [JsonProperty("item_subtype")]
        public string ItemSubtype { get; set; }

        [JsonProperty("type")]
        public ParentSet Type { get; set; }

        [JsonProperty("is_weapon")]
        public bool IsWeapon { get; set; }

        [JsonProperty("level")]
        public long Level { get; set; }

        [JsonProperty("pods")]
        public long Pods { get; set; }

        [JsonProperty("image_urls")]
        public ImageUrls ImageUrls { get; set; }

        [JsonProperty("effects")]
        public Effect[] Effects { get; set; }

        [JsonProperty("recipe")]
        public Recipe[] Recipe { get; set; }

        [JsonProperty("parent_set")]
        public ParentSet ParentSet { get; set; }
    }

    public partial class Effect
    {
        [JsonProperty("int_minimum")]
        public long IntMinimum { get; set; }

        [JsonProperty("int_maximum")]
        public long IntMaximum { get; set; }

        [JsonProperty("type")]
        public TypeClass Type { get; set; }

        [JsonProperty("ignore_int_min")]
        public bool IgnoreIntMin { get; set; }

        [JsonProperty("ignore_int_max")]
        public bool IgnoreIntMax { get; set; }

        [JsonProperty("formatted")]
        public string Formatted { get; set; }
    }

    public partial class TypeClass
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("is_meta")]
        public bool IsMeta { get; set; }

        [JsonProperty("is_active")]
        public bool IsActive { get; set; }
    }

    public partial class ImageUrls
    {
        [JsonProperty("icon")]
        public Uri Icon { get; set; }

        [JsonProperty("sd")]
        public Uri Sd { get; set; }

        [JsonProperty("hq")]
        public Uri Hq { get; set; }

        [JsonProperty("hd")]
        public Uri Hd { get; set; }
    }

    public partial class ParentSet
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }
    }

    public partial class Recipe
    {
        [JsonProperty("item_ankama_id")]
        public long ItemAnkamaId { get; set; }

        [JsonProperty("item_subtype")]
        public string ItemSubtype { get; set; }

        [JsonProperty("quantity")]
        public long Quantity { get; set; }
    }

    public partial class ItemData
    {
        public static ItemData FromJson(string json)
        {
            return JsonConvert.DeserializeObject<ItemData>(json, Converter.Settings);
        }
    }

    public static class Serialize
    {
        public static string ToJson(this ItemData self)
        {
            return JsonConvert.SerializeObject(self, Converter.Settings);
        }
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
